### ISSUE TITLE
Crashing on checking for availability

### ISSUE THREAD

**Issue by arshadkazmi42** [sindresorhus/npm-name-cli#17]
I have been using this tool for couple of weeks.
This is the first time I am getting this error, and its throwing only for this package name `n-mysql`

Command
`npm-name n-mysql`

Error

![Screenshot from 2019-03-10 09-50-22](https://user-images.githubusercontent.com/4654382/54080619-317d0b80-431a-11e9-84d1-71cea990699b.png)

**Comment by sindresorhus** [comment]
// @sholladay

**Comment by sholladay** [comment]
There's an open PR to fix this. I'll try to get it merged as soon as possible. I've had limited free time for it.

**Comment by sindresorhus** [comment]
For reference, this PR: https://github.com/sholladay/squatter/pull/2

**Comment by sholladay** [comment]
The fix for unpublished packages was released in `squatter@0.2.1`.

There seems to be a fair amount of bad data on the npm registry, some of which could still cause similar issues under certain circumstances. But I think this can be closed for now. There are other open issues for handling the malformed packages.
